// Dapps Incorporated 2020. All Rights Reserved.

public class BaselineProtocolMessageWrapper {
    
        @InvocableVariable(label='opcode')
        public String opcode;
        @InvocableVariable(label='sender')
        public String sender;
        @InvocableVariable(label='recipient')
        public String recipient;
        @InvocableVariable(label='shield')
        public String shield;
        @InvocableVariable(label='identifier')
        public String identifier;
        @InvocableVariable(label='signature')
        public String signature;
        @InvocableVariable(label='type')
        public String type;
        @InvocableVariable(label='payload')
        public String payload;
        

}